#!/bin/bash

if [ ! -z $1 ] ; then
	latex $1.tex
	bibtex $1
	latex $1.tex
	bibtex $1
	latex $1.tex
	latex $1.tex
	dvips -t letter -o $1.ps $1.dvi
	ps2pdf $1.ps $1.pdf

else
	echo "Usage: texit <tex file>"
fi

